apiVersion: v1 # k8s has a lot of different things we can pull from and use this is the default v1 list of objects we can create
kind: Pod # This is the type of object we are creating, in this case a pod
metadata: # different options we can set for the pod
  name: posts # name of the pod, this is what we will use to reference it in the future
spec: # the spec is where we define the details of the pod
  containers: # this is where we define the containers that will be running in the pod which is an array the - in yaml is used to denote an array
    - name: posts # name of the container, this is what we will use to reference it in the future
      image: caden43/posts:0.0.1 # The exact image we want to use for the container 